/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "IngestBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "SummarizeQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "TranscribeQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "WebApp": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
  }
}
